test:
  db_hostname:
  db_username:
  db_password:
  db_name:

  mailer_default_email_address:


development:
  db_hostname:
  db_username:
  db_password:
  db_name:

  mailer_default_email_address:


production:
  db_hostname:
  db_username:
  db_password:
  db_name:

  mailer_default_email_address: