test:
  db_hostname:
  db_username:
  db_password:
  db_name:

  mailer_default_email_address:

  sendgrid_list_id:
  sendgrid_auth_token:
  sendgrid_domain:

  capybara_screenshots_path:
  ci_true:

  devise_secret_key:
  devise_pepper_hash:

  github_client_id:
  github_secret_key:

  google_client_id:
  google_secret_key:

  twitter_client_id:
  twitter_secret_key:

  app_hostname:
  app_port:


development:
  db_hostname:
  db_username:
  db_password:
  db_name:

  mailer_default_email_address:

  sendgrid_list_id:
  sendgrid_auth_token:
  sendgrid_domain:
  
  devise_secret_key:
  devise_pepper_hash:

  github_client_id:
  github_secret_key:

  google_client_id:
  google_secret_key:

  twitter_client_id:
  twitter_secret_key:

  app_hostname:
  app_port:


production:
  db_hostname:
  db_username:
  db_password:
  db_name:

  mailer_default_email_address:

  sendgrid_list_id:
  sendgrid_auth_token:
  sendgrid_domain:
  
  devise_secret_key:
  devise_pepper_hash:
  
  github_client_id:
  github_secret_key:
  
  google_client_id:
  google_secret_key:

  twitter_client_id:
  twitter_secret_key:

  app_hostname:
  app_port: